### ISSUE TITLE
Amount calculation issues - Trading Page

### ISSUE THREAD

**Issue by aanandan1987** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1253]
Total Amount calculation issues

While making a Sell Trade we are entering Price and Amount column and based on these value Total amount is being calculated. and here a trimming happened in showing the amount. at times its been trimmed for 4 digits and at times for 5 digits

## Expected Behavior

Trimming to be happen for a fixed number and need to know ceiling or flooring happens here

## Current Behavior

unstable and getting 4 or 5 digits

## 🔎 Steps to Reproduce

1. Access the page
2. Go to trade
3. make a sell transaction

Tested on Windows and used chrome
![photo_2024-05-13_18-54-16](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/158262955/20ca391f-62af-47d4-b935-93e2a54fa4cd)
![photo_2024-05-13_18-54-12](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/158262955/6a0bf1a0-c38a-4f26-8f44-96523b2e5acd)

**Comment by ap211unitech** [comment]
The PR is up for fixing it. There was a issue with precision for `total` field when we change price.

**Comment by pavankanteti** [comment]
@aanandan1987 - Can you please confirm if this is fixed now?

**Comment by aanandan1987** [comment]
can see this rounding fraction issue as fixed. how ever noted another UI issue here.
Since we don't restrict on Amount column, putting a large value on Amount column affects the UI display. 

**Case 1 - UI looks good**
Price :0 .6238
Amount : 1
Total : 0.6238

**Case 2 - UI fails to show complete amount** 
Price :0 .6238
Amount : 11111111111
Total : 6931111111.0418
![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/158262955/74c9635c-e431-4415-8ad5-5946365347a1)

**Comment by ap211unitech** [comment]
Will be fixed soon.

**Comment by ap211unitech** [comment]
This is being fixed [here](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/1300).

**Comment by ap211unitech** [comment]
@aanandan1987  Can you test it again ?

**Comment by aanandan1987** [comment]
Can see that maximum of 4 digits fraction coming here now. looks good at the moment . 
![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/158262955/9f47bfd4-7ab0-48a5-8ef7-57fbd52d6a57)
