### ISSUE TITLE
There is an issue when a new user transfers the fund to a trading account

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1257]
# 📝 Bug Description
There is an issue when a new user transfers the fund to a trading account

## 🤔 Expected Behavior
If the transaction does not happen or gets any error the fees should not be deducted from the funding account. 

## 😯 Current Behavior
The user has 2 PDEX in the funding account, user transferred 1 PDEX to the trading account. got an error so the amount was not transfer to the trading account
but the fees were deducted from the funding account
![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/5dd3ef67-6f52-4b08-af00-aa98b58c5b35)

## 🔎 Steps to Reproduce

steps
Precondition -> Create a new funding account with a balance of 2PDEX
1. Navigate to Polkadex home page
2. Select polkadot extension
3. Select a newly created funding account
4. Displayed "Welcome to polkadex orderbook" pop-up window
5. Click the "Transfer funds" button
6. Navigate to the "Transfer" Page
7. Select the Asset 
8. Give the Amount ("1 PDEX") to transfer
9. Click the Transfer button
10. click the "sign and submit" button
11. Give a password for Polkadot to do the transaction
12. Click the "sign the transaction" button
13. Verify the user is able to do the transfer to the trading account

## 💁 Possible Solution
If the transaction does not happen or got any error then the fees should not be deducted from the funding account

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
Fee would be deduced first, always. Transaction may get unsuccesful that's how blockchain works.

**Comment by nuel77** [comment]
you can validate if balance - transfer_amount - tx_fee >= 1 PDEX for validation

**Comment by ap211unitech** [comment]
PR is raised for it.

**Comment by Hildajose** [comment]
Tested and verified
