### ISSUE TITLE
There is an issue in the orderbook page even after the user transfer the funds to trading account and navigates to orderbook page

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1258]
# 📝 Bug Description
There is an issue in the orderbook page even after the user transfer the funds to the trading account and navigates to orderbook page
Verify the Sell and Buy buttons

## 🤔 Expected Behavior
If the user transfer the amount to the trading account, the the user should able to the trade

## 😯 Current Behavior
In orderbook Sell and Buy buttons displayed "Fund Account" text and not able to make a trade

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/0629468f-61d8-457b-b945-5a722ccc5b67)

## 🔎 Steps to Reproduce

steps
Precondition -> Create a new funding account with a balance of 2PDEX
1. Navigate to Polkadex home page
2. Select polkadot extension
3. Select a newly created funding account
4. Displayed "Welcome to polkadex orderbook" pop-up window
5. Click the "Transfer funds" button
6. Navigate to the "Transfer" Page
7. Select the Asset 
8. Give the Amount ("0.9 PDEX") to transfer
9. Click the Transfer button
10. click the "sign and submit" button
11. Give a password for Polkadot to do the transaction
12. Click the "sign the transaction" button
13. Click Trade Tab
14. Verify the user is able to do the trade. Verify the sell and buy buttons

## 💁 Possible Solution
If the transaction does not happen or got any error then the fees should not be deducted from the funding account

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
This is fixed now. The behavior would be like this - 

1. New User transfer funds
2. It's account would be automatically selected for trading.
3. There would be no more `Fund Account` button again in exchange page. User will see `Buy` and `Sell` buttons directly.
