### ISSUE TITLE
There is an issue in orderbook page, the user not able to view the trading account details even after the user transfer the fund to trading account

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1259]
# 📝 Bug Description
There is an issue in orderbook page, the user not able to view the trading account details even after the user transfer the fund to trading account

## 🤔 Expected Behavior
The user should view the details of the trading account once user transfer the fund successfully to the trading account

## 😯 Current Behavior
The user should not able to view the trading account details even after the successful transaction to the trading account
Now user able to view trading account details only after the relog in to the account 

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/17636502-85c4-4f2f-99d0-c996147b89cc)

## 🔎 Steps to Reproduce

Precondition -> Create a new funding account with a balance of 2PDEX
1. Navigate to Polkadex home page
2. Select polkadot extension
3. Select a newly created funding account
4. Displayed "Welcome to polkadex orderbook" pop-up window
5. Click the "Transfer funds" button
6. Navigate to the "Transfer" Page
7. Select the Asset 
8. Give the Amount ("0.9 PDEX") to transfer
9. Click the Transfer button
10. click the "sign and submit" button
11. Give a password for Polkadot to do the transaction
12. Click the "sign the transaction" button
13. Click Trade Tab
14. click the funding account (on top right)
15. Verify the user able to view the Trading account details

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
If user is using his funding account for trading, he won't see it.
If he is using a trading account, then he will see something like this.

<img width="265" alt="image" src="https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/ae6c7fd4-9392-488c-96f6-480213b3271c">

This is the desired behavior.

**Comment by Hildajose** [comment]
Ok got it
