### ISSUE TITLE
There is an error displayed when user creates a 3rd trading account

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1261]
# 📝 Bug Description
There is an error displayed when the user creates a 3rd trading account. so not able to create the 3rd trading account(!trading account automatically created and 2nd trading account user created and when user try to create the 3rd trading account there is a error displayed

## 🤔 Expected Behavior
The user should able to create a 3rd trading account.

## 😯 Current Behavior
There is an error message displayed when a user creates the 3rd trading page.
After refreshing the page and trying to create the 3rd trading account without any error it was created successfully

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/a73aa9c6-c9d1-45fe-92a7-6400ade0f90f)

## 🔎 Steps to Reproduce

1. Navigate to Polkadex home page
2. Select polkadot extension
3. Select a newly created funding account
4. Displayed "Welcome to polkadex orderbook" pop-up window
5. Click "Transfer funds" button
6. Navigates to the "Transfer" Page
7. Select the Asset 
8. Give the Amount to transfer
9. Click Transfer button
10.click "sign and submit" button
11. Give password for Polkadot to do the transaction
12. Click "sign the transaction" button
13. Fund transfered to the trading account
14.Click Trade Tab
15. Click Funding account (top right corner)
16. Click Options button
17. Click "create new Trading account" button(3rd trading account)
18. "Confirm Trasaction" pop-up displayed
19. Give password and click "sign and submit" button
20. Verify the user able to transfer the estimation fee and create new trading account 

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
This is fixed now.

**Comment by Hildajose** [comment]
working fine
