### ISSUE TITLE
There is an issue when the user places a Market sell order(Sell PDEX), after successfully placing the order the receiver assets(USDT) do not get updated until refresh the page

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1262]
# 📝 Bug Description
There is an issue when the user places a Market sell order(Sell PDEX), after successfully placing the order the receiver assets(USDT) do not get updated until refresh the page

## 🤔 Expected Behavior
Without refreshing the page the tokens should updated properly

## 😯 Current Behavior
After refresh the page only its get updated

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/716d2993-7484-459c-9ed9-ee772b49cec5)

## 🔎 Steps to Reproduce
1. Navigate to Polkadex home page
2. Select polkadot extension
3. Select a newly created funding account
4. Displayed "Welcome to polkadex orderbook" pop-up window
5. Click "Transfer funds" button
6. Navigates to the "Transfer" Page
7. Select the Asset 
8. Give the Amount to transfer
9. Click Transfer button
10.click "sign and submit" button
11. Give password for Polkadot to do the transaction
12. Click "sign the transaction" button
13. Fund transfered to the trading account
14.Click Trade Tab
15. click Market tab
16. Give the Amount
17. Click Sell button
18. Verify the user able to place a sell order 

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
I am not able to re-create it. It's working fine for me.

**Comment by Hildajose** [comment]
You can verify the image I posted, only after refreshing the page only I get the correct update

**Comment by Hildajose** [comment]
now its working properly
