### ISSUE TITLE
Accumulate amount for same price in Orderbook

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1267]
## 📝 Bug Description

In Orderbook component, there is a dropdown for changing price tick size but it's behavior is not working as expected. Ideally, when we change the price tick size, amount for same price should accumutate and volume should be calculated accordingly. 

But the current behavior is, it just applied the tick size for price, but don't affact amount and volume at all.

Basically, Orderbook cannot contain same price more than once. that's the ideal behavior. If there are same prices, it's amount must be accumulated.

## 😯 Current Behavior

https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/bf479e65-04d4-4a84-a8f9-51eae01cc87f

## 🤔 Expected Behavior

<img width="350" alt="image" src="https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/8ed0f599-91a1-40df-bc1a-3c2c89d6a8f0"> <img width="350" alt="image" src="https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/25728cc8-14a6-44a0-b6b4-95b5893d4cf7">

**Comment by jaymansfield** [comment]
Resolving this will also close https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/issues/350
