### ISSUE TITLE
Need more than 1PDEX to create extension

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1269]
# 📝 Bug Description
UI displayed as user need "required balance as 1 PDEX" but if user put the 1PDEX into the user's funding account, that user is not able to create the extension trading account because there is a limit for funding account as 1PDEX. 

 In old UI displayed as user needs 2PDEX to create a trading account

## 🤔 Expected Behavior
The user has to transfer at least 2 PDEX to the funding account after that allow the user to create extension trading account

## 😯 Current Behavior
Even if the user put min. balance required ie 1PDEX to his funding account, that user is not able to create the extension trading account. because there is a 1 PDEX limit for funding account

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/9abed9db-8914-4c91-88bf-0cafca5fb578)
![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/8b05858f-92c6-4eaf-8bda-69b9b6e48cb1)

## 🔎 Steps to Reproduce

1.create new user with 1 PDEX in funding account
2.select the funding account
3. click the "Transfer fund" button
4. navigates to the Transfer page
5. Verify the user able to create the extension trading account with 1PDEX balance in the funding account

## 💁 Possible Solution
Make required balance as 2 PDEX

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
Will change it to `> 1 PDEX` in PopUp.

**Comment by ap211unitech** [comment]
Can not put false information like 2 PDEX

**Comment by Hildajose** [comment]
@ap211unitech Now not able to add extension trading account. 
there is no pop-up displaying to add extension trading account. so not able to check this issue. 
ref. video


https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/014b5f43-95d9-49b5-b90c-ad284fae35e9
