### ISSUE TITLE
Issue: User lost 1 PDEX amount 

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1273]
# 📝 Bug Description
When the user transfers the maximum PDEX amount to another funding account, the funding account balance comes to zero. So the user losing his 1 PDEX

## 🤔 Expected Behavior
If the user transfers the maximum PDEX amount to another funding account, the funding account balance amount should be displayed

## 😯 Current Behavior
if the user transfers the maximum PDEX amount to another funding account, the user's funding account displays zero

## 🔎 Steps to Reproduce

1. Login with the funding account
2. Select Balance Tab
3. Select the Transfer button
4. Select PDEX
5. Select Another funding account from the drop-down
6. set the funding account to be transfer
7. click the Max button to transfer the maximum amount from the user's account to another funding account
8. Click Transfer button
9. Sign and submit polkadot
10. Verify the PDEX balance after the Transfer

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
[Subscan](https://polkadex.subscan.io/extrinsic/0x677c579073cdc545551aff6d69656ba03595858b57dfa7983f1b049536b74d7a)

**Comment by Hildajose** [comment]
Tested and its working fine
