### ISSUE TITLE
The no trading account pop_up remains even after account created

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1278]
# 📝 Bug Description
Even After Creating extension Trading account, the pop_up remains

## 🤔 Expected Behavior
After creating the extension trading account, "no trading account found in browser" pop-up should be closed

## 😯 Current Behavior
After creating the extension trading account, "no trading account found in browser" pop-up is not closed

https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/c26dc4a1-2dde-4980-ab7b-11a3db5fc785

## 🔎 Steps to Reproduce

1. Login with the funding account
2. click "Register funding account"
3. create an extension trade account (1st trading account)
4. sign and submit polkadot
5. verify the "no trading account found in browser" pop-up should be closed after create the trading account

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
This is being fixed [here](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/1300).

**Comment by ap211unitech** [comment]
@Hildajose Can you test it again ?

**Comment by Hildajose** [comment]
Tested and verified
