### ISSUE TITLE
There is a difference in calculation on Sell and Buy section

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1286]
# 📝 Bug Description
There is a difference in calculation on the Sell section 
when the user enters the value in the Total field, the amount is calculated automatically but if the user give the same calculated value in the Amount field first, the Total value is calculated differently

## 🤔 Expected Behavior
The calculation should displayed properly if the user enters the value in the "Amount" field first or  enters  the value in the "Total" field first 

## 😯 Current Behavior
Displaying different values, in order this issue the user is not able to place the sell or buy order if the user enters the value in the "Total" field first the amount is calculated automatically then click the sell button. an error message displayed
 

when user enter the value in the total field
![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/499be4d8-5c74-4796-bf1f-920bfcf77bb4)
when the user enter the amount field 
![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/77cabe9e-4de5-48be-83ae-3c7964f58149)

## 🔎 Steps to Reproduce

case 1
1. Login with funding account
2. Enter the value in the Total field
3. verify the value in the amount field

case 2
1. Login with the funding account
2. Enter the value in the Amount field
3. verify the value in the Total field

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
@Hildajose @aanandan1987 

**CASE I - (When we put volume/total first)** 

Amount = Total / Price (with some precision)

**CASE II - (When we put amount first)** 

Total = Price * Amount (with some precision)

As, there is different logic for calculating values in both cases, so it can't be the same always. Also, There are some centralized exchanges like Kucoin, the similar behavior can be noticed there. Check the attacted clip here.

https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/1e8ea103-874c-49cc-ac8a-eee4e9544c13

I hope that makes it clear. Let me know if you have any doubts.
