### ISSUE TITLE
Wrong ASTAR balance displayed

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1287]
# 📝 Bug Description
after successfully depositing ASTAR to Polkadex, the wrong balance is displayed

## 🤔 Expected Behavior
The proper balance to be displayed after the successful deposit

## 😯 Current Behavior
There is a wrong balance displayed after deposit the maximum value to the polkadex network

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/3c92537c-c891-4818-b892-cae510972b4c)
 when I open in https://deploy-preview-1281--stupendous-valkyrie-505e4a.netlify.app/thea?from=Astar&to=Polkadex&asset=ASTR link, verify the screenshot
![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/5b222fdf-9648-4284-97f7-604db1395aa8)

## 🔎 Steps to Reproduce

1. login with funding account
2. Select the funding account in "From and "To" section
3. select the From network as ASTAR and To network as Polkadex
4. select the Max button
5. click Bridge button
6. sign and submit for polkadot
7. verify the user is able to view the current balance

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
This is not the correct link which you are using for testing. Please use the correct one. Let me know if you able to recreate this issue there.

**Comment by ap211unitech** [comment]
This is fixed

**Comment by Hildajose** [comment]
tested and Verifyed
