### ISSUE TITLE
 The fees are deducted from the PDEX without any action

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1288]
# 📝 Bug Description 
The fees deducted from the PDEX even after the error occurs in between transaction

## 🤔 Expected Behavior
If the transaction does not happen the fees should not be deducted from the PDEX balance

## 😯 Current Behavior
The fees deducted from the PDEX even after the error occurs in between transaction

https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/7a6fe6b9-950e-494d-bb19-a5ffff7ca73f

## 🔎 Steps to Reproduce

1. login with funding account
2. Select the funding account in "from" section and "To" section
3. set the Amount
4. click "Budget" button
5. sign and submit for pokadot
6. error message displayed
7. verify the fees deducted from the PDEX

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
First of all, this is not the correct link which you are using for testing THEA.
For fee, it always deducts fee once your signed the transaction, transaction may get fail but fee would be always deducted. It is a quite small amount ~ 0.02 PDEX , that's how the blockchain works basically.
