### ISSUE TITLE
Couple minor things on internal page

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1289]
"Fund account" area still points to old thea.polkadex.trade rather then new bridge page.

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/6218678/b7f6786d-0336-4dc4-91e9-7e2d9bb61203)

Transaction section for the bridge is titled "Thea History", but on the bridge page there is no mention of the word Thea. Users may not know these are related.
![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/6218678/ec4ef109-050b-43fc-8e8d-4992837ccc00)

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/6218678/bee51d27-d432-4ab6-b843-d2c300169173)

Also is it Thea or THEA. Should try to be consistent for branding purposes.

**Comment by ap211unitech** [comment]
Hey @jaymansfield , This issue is resolved now in this [PR](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/1281) along with some more bugs. However, the PR is not merged yet.
