### ISSUE TITLE
Percentage calculation issues on Trading page

### ISSUE THREAD

**Issue by aanandan1987** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1291]
# 📝 Bug Description

Percentage calculation is not stable in Trading page

## 🤔 Expected Behavior

should be getting the correct percentage amount on UI based on user selection
Got a balance of 2 PDEX and it should show my percentage calculation like below
25 % -> 0.5
50 % -> 1
75 % -> 1.5
100 % -> 2

## 😯 Current Behavior

At times its showing different values for percentage calculation 
Got a balance of 2 PDEX
25 % -> 0.4999
![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/158262955/d4de3759-a7fb-4a63-a790-c5221df7005b)

50 % -> 1
75 % -> 1.5
100 % -> 1.9999
![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/158262955/c368dfaa-2678-4ec1-88a5-c285899bb416)

## 🔎 Steps to Reproduce

1. Go to Trading page

2. try with percentage buttons to see its showing correctly 

## 🌍 Your Environment
https://orderbook.polkadex.trade/trading/PDEXUSDT

**Comment by ap211unitech** [comment]
This is being fixed [here](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/1294).

**Comment by ap211unitech** [comment]
@aanandan1987 Can you please test it again ? Use this [url](https://orderbook-internal.polkadex.trade/) to test it. It will be merged to production soon.

**Comment by aanandan1987** [comment]
tried multiple attempts and can see its working as expected at the moment.  closing it for now
