### ISSUE TITLE
Bridge page issue : Not able to do withdraw

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1295]
# 📝 Bug Description
There is an issue when a user tries to the withdraw from Polkadex to ASTAR network

## 🤔 Expected Behavior
Error message displayed

## 😯 Current Behavior
The user should not be able to do the withdrawal. The "Asset not registered" alert message displayed

https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/05527157-76d8-424e-95d0-79a1181fdc4d

## 🔎 Steps to Reproduce

1. Login with funding account
2. select the From Network as Polkadex
3. select the destination network as ASTAR
4. set the amount
5. Click the "Bridge" button
6. Sign and submit for polkadot
7. verify the user able to do the withdrawal

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
@Hildajose Can you test it again & close it?

**Comment by Hildajose** [comment]
Tested and verified
