### ISSUE TITLE
Buy and Sell button are enabled by default

### ISSUE THREAD

**Issue by aanandan1987** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1301]
# 📝 Bug Description

On the trading page can see that Buy PDEX and Sell PDEX buttons are enabled by default.  there are no check performed at this stage and still both pf them are enabled. 

## 🤔 Expected Behavior

Buttons Should be disabled by default. 

## 😯 Current Behavior

Both are enabled as default. 
![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/158262955/ba8be356-ab61-44fc-a5fb-ab77ee1fc2a3)

## 🔎 Steps to Reproduce

1. Login to the platform 
2. Click on Trade section

## 🌍 Your Environment

https://orderbook.polkadex.trade/trading/PDEXUSDT

**Comment by ap211unitech** [comment]
This is not an issue. This is desired behavior. If user doesn't touches the form, it will be enabled always.

**Comment by aanandan1987** [comment]
@ap211unitech then it should be the same case with Market Tab as well. right ?
![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/158262955/c6274bd0-3a21-4f29-a78d-d37fa7250672)
