### ISSUE TITLE
Bridge bugs related to Text displayed

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1307]
# 📝 Bug Description
Need to improve the text displayed for warning message
1.**Withdraw_From Network_Estimation fees_ not enough PDEX balance**
**steps**
1. Open web url https://orderbook-internal.polkadex.trade/
 2. Click on the "Bridge" tab
 3. Select From Network as "Polkadex" from the From Dropdown.
4. Click the To Network Dropdown button.
5. Select the To Network as "Polkadot"
6.Select any Asset From token dropdown
7.Enter the valid amount
8. Click Bridge button
9. Click Sign and Submit button for Polkadot
10. Successful message is displayed.
11. Verify the user is not able to proceed the Withdraw action without the PDEX balance in(From Network)

**Actual result**
Proper error message is not displayed. Now "Token : Not Expendable" message displayed.

2. **cancellation**

**step**
1. Open web url https://orderbook-internal.polkadex.trade/
2. Click on the "Bridge" tab
3. Select the From Network from the From Dropdown
4.Click "Connect wallet" button under the Networks From button and add a account
5.Select the To Network from the To Drop down.
6. Click the "Select or enter a Polkadex address" under the Networks To button and add the To address
7. Enter the valid amount based on the Available balance of the token.
8. click the Bridge button
9. Click sign in and submit
9. Verify the user able to click cancel button

**Actual result**
User receiving "Cancelled" message, improve the text when user cancel the order

**Comment by pavankanteti** [comment]
already fixed these

**Comment by Hildajose** [comment]
Verified
