### ISSUE TITLE
Issue in withdraw(DOT,DED & PINK)

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1311]
# 📝 Bug Description
There issue with the withdrawal of DOT, DED and PINk in the funding account address: 5DF4wGcJ2FHtiA8XRgRAmkAGHTHFuZBW2ajQ2fcmwbooPMoh

## 🤔 Expected Behavior
If a user makes the withdrawal of the amount, that amount should be updated in the destination network

## 😯 Current Behavior
If a user makes the withdrawal of DOT, DED, and PINK, the amount is not updated in the destination network. The fees and amount were deducted from the Polkadex network but were not updated in the destination network.

https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/bee90bf1-7a1f-4e69-b347-bf18d360ba66

## 🔎 Steps to Reproduce

1. Click bridge
2. select the "From network" as polkadex
3. Select the funding account as 5DF4wGcJ2FHtiA8XRgRAmkAGHTHFuZBW2ajQ2fcmwbooPMoh
4. select the "To network" as **Polkadot/Assethub(PINK)/Assethub(DED)**
5. Select the funding account as 5DF4wGcJ2FHtiA8XRgRAmkAGHTHFuZBW2ajQ2fcmwbooPMoh
6. St thee amount
7. Click the Bridge
8. sign and submit for polkadot
9. verify the user is able to get the updates in the destination networks

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment]
This is being fixed [here](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/1312).

**Comment by ap211unitech** [comment]
@Hildajose Can you test it again. Test for vDOT as well.

**Comment by Hildajose** [comment]
Tested and verified
